name: Azure Pipelines
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted Ubuntu 1604
      image: "ubuntu-latest"
    steps:
    - task: CmdLine@1
      displayName: Install Newman
      inputs:
        script: 'sudo npm install -g newman'
        workingDirectory: '.'
    - task: CmdLine@2
      displayName: Test Starter API by Newman
      continueOnError: true
      inputs:
        script: 'newman run StarterAPIs.json'
        workingDirectory: '.'

    