name: Azure Pipelines
pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: CmdLine@2
      displayName: Install Newman
      inputs:
        script: 'sudo npm install -g newman'
        workingDirectory: '.'
    - task: CmdLine@2
      displayName: Test Starter API by Newman
      continueOnError: true
      inputs:
        script: 'ls -la'

    